# Generated by Django 3.2.3 on 2021-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_line_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='coda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('goal_time', models.DateTimeField(auto_now_add=True)),
                ('groupID', models.CharField(default='', max_length=50)),
                ('end', models.BooleanField(default=False)),
                ('lowest_num', models.DecimalField(decimal_places=0, max_digits=3)),
                ('answer_num', models.DecimalField(decimal_places=0, max_digits=3)),
                ('height_num', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
