# Generated by Django 3.2.3 on 2021-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_coda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coda',
            name='answer_num',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='coda',
            name='height_num',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='coda',
            name='lowest_num',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
